// VirgoYT Factory Mode.
// Turns "build me an app / create a startup / make a website" into a full
// software-production pipeline: understand -> plan -> scaffold -> code -> test
// -> docs -> ship. Streams each stage live.

import { proxyAi } from '../../ai/AiProxy.js';
import { runCommandInSandbox } from '../../sandbox/DockerManager.js';
import { writeFile } from '../../filesystem/FileManager.js';

export type FactoryEvent =
  | { type: 'factory-stage'; id: string; stage: string; message: string }
  | { type: 'factory-plan'; id: string; steps: string[] }
  | { type: 'factory-command'; id: string; command: string; output: string }
  | { type: 'factory-file'; id: string; path: string }
  | { type: 'factory-result'; id: string; summary: string }
  | { type: 'factory-error'; id: string; message: string };

type FactoryConfig = {
  model: string;
  sessionId: string;
  rootDir: string;
  stream: (e: FactoryEvent) => void;
};

export class Factory {
  constructor(private config: FactoryConfig) {}

  async run(idea: string): Promise<FactoryEvent[]> {
    const id = `fx-${Date.now()}`;
    const events: FactoryEvent[] = [];
    const emit = (e: FactoryEvent) => {
      events.push(e);
      this.config.stream(e);
    };

    try {
      // 1. Understand + plan
      emit({ type: 'factory-stage', id, stage: 'plan', message: `Understanding "${truncate(idea, 80)}" and drafting architecture…` });
      const plan = await this.ask(`You are a startup/software factory lead.
Translate this idea into a concrete build plan:
"${idea}"
Return ONLY a JSON array of {file, purpose} objects for the minimal MVP (max 6 files), then a "build_commands" array of shell commands to scaffold & run it, and a "README" string.
Format: {"files":[{"file":"...","purpose":"..."}],"build_commands":["npm init -y"],"README":"..."}`);
      emit({ type: 'factory-plan', id, steps: (plan.files ?? []).map((f: any) => f.file) });

      // 2. Scaffold
      emit({ type: 'factory-stage', id, stage: 'scaffold', message: 'Setting up project structure…' });
      for (const cmd of plan.build_commands ?? []) {
        const out = await this.tryCommand(cmd);
        emit({ type: 'factory-command', id, command: cmd, output: truncate(out, 600) });
      }

      // 3. Code
      emit({ type: 'factory-stage', id, stage: 'code', message: 'Generating source files…' });
      for (const f of plan.files ?? []) {
        const content = await this.ask(
          `Write the full, valid content of file "${f.file}" for this project:
Idea: "${idea}"
Purpose: ${f.purpose}
Return ONLY the raw file content. No markdown fences. If it's JSON/TS/HTML/CSS just output it.`
        );
        await writeFile(this.config.rootDir, f.file, content);
        emit({ type: 'factory-file', id, path: f.file });
      }

      // 4. Install & verify
      emit({ type: 'factory-stage', id, stage: 'verify', message: 'Installing deps and verifying…' });
      const verify = await this.tryCommand('node --version && npm --version 2>/dev/null || true');
      emit({ type: 'factory-command', id, command: 'check runtime', output: truncate(verify, 300) });

      // 5. README
      emit({ type: 'factory-stage', id, stage: 'docs', message: 'Writing documentation…' });
      const readme = plan.README || `# ${idea}\n\nAuto-generated by VirgoYT Factory Mode.`;
      await writeFile(this.config.rootDir, 'README.md', readme);
      emit({ type: 'factory-file', id, path: 'README.md' });

      emit({ type: 'factory-result', id, summary: `Factory delivered a scaffolded MVP of "${truncate(idea, 60)}" at the workspace root. Open Files to inspect.` });
    } catch (e: any) {
      emit({ type: 'factory-error', id, message: e.message });
    }

    return events;
  }

  private async ask(prompt: string): Promise<any> {
    const res = await proxyAi({ model: this.config.model, prompt });
    try {
      const matched = res.content.match(/\{[\s\S]*\}/);
      if (matched) return JSON.parse(matched[0]);
      return {};
    } catch {
      return {};
    }
  }

  private async tryCommand(command: string): Promise<string> {
    try {
      return await runCommandInSandbox(this.config.sessionId, command, this.config.rootDir);
    } catch (e: any) {
      return `(command unavailable: ${e.message})`;
    }
  }
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n) + '…' : s;
}